Shooter: Fix for #3, Create a new shooter subsystem
FRC-1721/1721-RapidReact pull request #28
Opened 2022-02-13 20:24 UTC by KenwoodFox

Create a shooter subsystem

2022-02-15 23:08 UTC, KenwoodFox commented on rio/subsystems/yoke.py
> +                return 60 #returns maximum
This is a mess

2022-02-16 13:56 UTC, KenwoodFox reviewed
This does not work at all.

2022-02-16 22:41 UTC, KhanSimeoni approved these changes

2022-02-16 22:41 UTC, KhanSimeoni commented on rio/subsystems/yoke.py
> +        self.portShooter.set(ControlMode.PercentOutput, -speed)
Should we be setting the shooter speed to a flat 0 or 1? we probably need a more variable speed for launch angles

2022-02-16 22:42 UTC, KhanSimeoni requested changes
Oops wrong button I meant to request  changes

2022-02-17 13:42 UTC, KenwoodFox commented on rio/subsystems/yoke.py
> +        self.portShooter.set(ControlMode.PercentOutput, -speed)
True but only sloppyshooter calls set speed.

We should idealy have a `setVelocity()` function that can take a value in m/s and set the PID on the shooters

2022-02-17 22:22 UTC, KenwoodFox commented on rio/subsystems/yoke.py
> +        )  # updating the pid target
Kicker dosent need pid, its just a kicker

2022-02-19 20:01 UTC, closed without merging