Feature/climber
FRC-1721/1721-RapidReact pull request #32
Opened 2022-02-15 22:58 UTC by Kredcool

Once this is done we should merge it

2022-02-15 23:04 UTC, KhanSimeoni approved these changes
Its a good start, we'll have to update it later but we can work with this

2022-02-15 23:04 UTC, KhanSimeoni commented on rio/subsystems/climber.py
> +        self.starboardClimber.follow(self.portClimber, True)
Follower looks good

2022-02-15 23:12 UTC, KenwoodFox commented on rio/subsystems/climber.py
> +        self.portClimber.SetReference(10)
Every 5s?
And timer needs to be spawned in `__init__`

2022-02-15 23:13 UTC, KenwoodFox requested changes
Fix background timer.

2022-02-17 18:35 UTC, KenwoodFox requested changes
- [x] Check if constants has variables
 - [ ] Implement climber in robotcontainer.py
 - [ ] Implement at least one command to control this subsystem
 - [ ] Remove any loop holdup inside climber.py, if commands want to limit the update speed thats where you would do this

2022-02-17 18:35 UTC, KenwoodFox commented on rio/subsystems/climber.py
> +        self.Climber_const = constants["Climber"]
Does this exist in the constants yet?

2022-02-17 18:35 UTC, KenwoodFox commented on rio/subsystems/climber.py
> +        self.starboardClimber.follow(self.portClimber, True)
Great!

2022-02-17 18:35 UTC, KenwoodFox commented on rio/subsystems/climber.py
> +        self.backgroundTimer.start()
This is not needed.

2022-02-17 18:35 UTC, KenwoodFox commented on rio/subsystems/climber.py
> +        self.backgroundTimer.hasPeriodPassed(5)
Not needed, do not holdup the updates here. only commands should implement delay

2022-02-17 22:21 UTC, KenwoodFox requested changes

2022-02-17 22:21 UTC, KenwoodFox commented on rio/constants/robot_hardware.yaml
> +    pose_y: 1 # updated 2/17/22 by keegan
These dont need poses?

2022-02-17 22:21 UTC, KenwoodFox commented on rio/constants/robot_hardware.yaml
> +    steer_id: 10 # updated 2/17/22 by keegan
Pfff, what?!

2022-02-17 22:21 UTC, KenwoodFox commented on rio/constants/robot_hardware.yaml
> +    steer_id: 12 # updated 2/17/22 by keegan
We only need two ids, what is this?

2022-04-08 01:36 UTC, merged